<?php
session_start();
$username=$_POST['username'];
$password=$_POST['password'];
$con=mysqli_connect('localhost','root','','SRM','3306');
mysqli_select_db($con,'SRM');
$q="select * from user where Username='$username'";
$result=mysqli_query($con,$q);
$num=mysqli_num_rows($result);
if($num==1)
{
    while($row=mysqli_fetch_assoc($result))
    {
        if(password_verify($password,$row['Password']))
        {
            $_SESSION['username']=$username;
            header("location:http://localhost/SRM/Home.php");
        }
        else
        {
            header("location:http://localhost/SRM/Login.php");
        }
    }
}
else
{
    header("location:http://localhost/SRM/Login.php");
}
mysqli_close($con);
?>